name: NeurDE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24
  - matplotlib
  - scipy
  - ipython
  - tqdm
  - h5py
  - pyyaml
  - yaml
  - pip:
    - torch